
# Port to listen on
listen-port = 6969

# Code highlighting styles can be found here:
# https://xyproto.github.io/splash/docs/all.html
code-highlighting-style = "doom-one2"

# THESE ARE TEMPORARY AND JUST FOR TESTING
# DONT USE SENSITIVE INFO
username = "" 

password = ""
